
sonar.organization=yogaekapratama29
sonar.projectKey=yogaekapratama29_VotingApp_TubesKPL
sonar.projectName=VotingApp_TubesKPL


sonar.sources=.

sonar.exclusions=node_modules/**, public/**, views/**


sonar.tests=test
sonar.test.inclusions=**/*.test.js


sonar.sourceEncoding=UTF-8
